commands:
  enabled: true
  prefix: '>'
  channels: ['1229769887056920597']
  overrides:
    - name: 'ban'
      roles: ['1230864906497298453', '1229769858594377771', '1229769856602345565', '1230864876591779941', '1229769854278434888']

    - name: 'remove-punishment'
      roles: ['1229769858594377771', '1229769856602345565', '1230864876591779941', '1229769854278434888']

punishments:
  editors: ['1230864906497298453', '1229769858594377771', '1229769856602345565', '1230864876591779941', '1229769854278434888']
  managers: ['1229769858594377771', '1229769856602345565', '1230864876591779941', '1229769854278434888']

  defaultWarnDuration: 2592000000 # 1 month
  defaultMuteDuration: 21600000 # 6 hours

  additionalInfo:
    warn: 'If you feel like this punishment is unjustified, you may appeal it by messaging a Mod**+** or above.'
    mute: 'If you feel like this punishment is unjustified, you may appeal it by messaging a Mod**+** or above.'
    kick: 'If you feel like this punishment is unjustified, you may appeal it by messaging a Mod**+** or above.'
    ban: 'If you feel like this punishment is unjustified, you may appeal it by messaging a Mod**+** or above.'

lock:
  channels: ['1229769880488771645', '1229769872754606130', '1229769885492711506', '1229769887056920597', '1229769883156353076', '1229769888290045992', '1229769877259292812', '1229769879494725663']
  overrides: 377960303168 # Will deny Send Messages, Send Messages In Threads, Create Public/Private Threads, Attach Files, Add Reactions, Connect (vc), Speak (vc), Video (vc)

tags:
  - name: '1'
    aliases: ['respect', 'toxic']
    embed:
      color: 0x1e1f22
      fields: 
        - name: "💞  Respect everyone at all times."
          value: "Hate speech, toxicity and/or harassment is strictly prohibited."
          inline: false
  - name: '2'
    aliases: ['mature', 'maturity']
    embed:
      color: 0x1e1f22
      fields: 
        - name: "🔔 Act mature when interacting in our community."
          value: "Spamming, begging and being annoying is prohibited."
          inline: false
  - name: '3'
    aliases: ['sfw', 'nsfw']
    embed:
      color: 0x1e1f22
      fields: 
        - name: "🔞  No inappropriate contributions."
          value: "This is not the place for NSFW images, messages or profiles. The same goes for overly sexual/suggestive conversations as well as sending unrelated links as we cannot keep our community safe outside of our community."
          inline: false
  - name: 'mod'
    aliases: ['apply', 'staff']
    embed:
      color: 0x1e1f22
      fields: 
        - name: "How do I apply for staff?"
          value: "To become a staff member, you must apply through our staff application. This form is available in <#1233676044070944810> when we require more staff, and you'll usually require around Level 25+ and 3 or less warnings to apply (but this may change)."
          inline: false
  - name: 'ranks'
    aliases: ['trusted', 'res']
    embed:
      color: 0x1e1f22
      fields: 
        - name: "How do I get the Trusted/Resident rank in-game?"
          value: "To learn more about the `[T]` rank, what it is and how to get it, check out the <#1233676674550337577> channel. If you want to get the `[Res]` rank, you will need to donate at least $5 USD via PayPal. More information can be found here: https://discord.com/channels/1169969721962151936/1233676044070944810/1233694955734831156"
          inline: false

reports:
  user: # User Reports
    enabled: true # A boolean (true/false)
    channelId: '1229769898327281684' # The channel in which message reports will be logged
    excluded: ['1229769856602345565', '1230864876591779941'] # An array of role ids immune to message reports
    blacklist: ['1229769864194031640'] # An array of role ids blacklisted from creating message report

  message: # Message Reports
    enabled: true # A boolean (true/false)
    channelId: '1229769898327281684' # The channel in which message reports will be logged
    excluded: ['1229769856602345565', '1230864876591779941'] # An array of role ids immune to message reports
    blacklist: ['1229769864194031640'] # An array of role ids blacklisted from creating message report
          
automod:
  filters:
    - name: 'No Swear Filter'
      enabled: false
      immuneRoles: ['1229769858594377771', '1229769856602345565', '1230864876591779941']
      immuneChannels: []
      punishment: 'Warn'
      duration: 1814400000
      customInfo: 'We are a SFW server, please do not use swear words.'
      fallbackResponse: 'Please do not send prohibited words!'
      content: ['word1', 'word2', 'word3']

    - name: 'No Slur Filter'
      enabled: false
      immuneRoles: ['1229769858594377771', '1229769856602345565', '1230864876591779941']
      immuneChannels: []
      punishment: 'Ban'
      customInfo: 'We are a welcoming and inclusive community, as such we will not tolerate any slurs.'
      fallbackResponse: "Slurs aren't welcome here buddy. Goodbye."
      content: ['slur1', 'slur2', 'slur3']

  links:
    - name: 'All Links Filter'
      enabled: true
      immuneRoles: ['1230867655301402644', '1229769858594377771', '1229769856602345565', '1230864876591779941']
      immuneChannels: []
      punishment: 'Warn'
      duration: 1814400000
      customInfo: 'You are not allowed to send any links as they may contain malicious content.'
      fallbackResponse: 'Hi! Please do not send links, thanks!'
      whitelist: ['discord.com', 'discordapp.com', 'tenor.com'] # We whitelist the domain in the global filter but not in the tenor filter that gets triggered for users without any of the immune roles.

    - name: 'Tenor Links Filter'
      enabled: true
      immuneRoles: ['1229769858594377771', '1229769856602345565', '1230864876591779941', '1230867655301402644', '1229769859835891743', '1229769861207560192', '1180061563382677536']
      immuneChannels: []
      punishment: 'Warn'
      duration: 1814400000
      fallbackResponse: 'Hi! You cannot send tenor links yet as you are lacking an immune role to the tenor links filter!'
      whitelist: []

  mentions:
    - name: 'Owner Mention Filter'
      enabled: true
      immuneRoles: ['1230867349029130371', '1230865029486870588', '1230864906497298453', '1229769858594377771', '1230865761040601108', '1229769856602345565', '1230864876591779941', '1229769854278434888']
      immuneChannels: []
      punishment: 'Warn'
      duration: 1814400000
      fallbackResponse: 'Hi! You cannot ping the owners as they are busy and will not respond to your message.'
      list: ['851803979914805328']

    - name: 'Developer Mention Filter'
      enabled: false
      immuneRoles: []
      immuneChannels: []
      punishment: 'Warn'
      duration: 1814400000
      fallbackResponse: 'Hi! You cannot ping the developers as they are busy and will not respond to your message.'
      list: ['1005206283596611614']

  antiSpam:
    maxMentions:
      enabled: true
      immuneRoles: ['1230867349029130371', '1230865029486870588', '1230864906497298453', '1229769858594377771', '1230865761040601108', '1229769856602345565', '1230864876591779941', '1229769854278434888']
      immuneChannels: []
      punishment: 'Warn'
      duration: 1814400000
      limit: 5

    maxCharacters:
      enabled: true
      immuneRoles: ['1230867349029130371', '1230865029486870588', '1230864906497298453', '1229769858594377771', '1230865761040601108', '1229769856602345565', '1230864876591779941', '1229769854278434888']     
      immuneChannels: []
      punishment: 'Warn'
      duration: 1814400000
      limit: 400

    maxAttachments:
      enabled: true
      immuneRoles: ['1230867349029130371', '1230865029486870588', '1230864906497298453', '1229769858594377771', '1230865761040601108', '1229769856602345565', '1230864876591779941', '1229769854278434888']
      immuneChannels: ['1229769888290045992', '1229769880488771645']
      punishment: 'Warn'
      duration: 1814400000
      limit: 8

logging:
  punishments:
    enabled: true
    channelId: '1229769901925994547'
  punishmentEdit:
    enabled: true
    channelId: '1229769901925994547'
  messages:
    enabled: true
    channelId: '1229769903217577985'
    excluded: ['']
  commands:
    enabled: false
    channelId: '1170309999352872970'
  mediaConversion:
    enabled: false
    channelIds: '1219614615172808755'
    logChannelId: '1183711455007219732' 
