commands:
  enabled: true
  prefix: '!'
  channels: []
  overrides:
    - name: 'ban'
      roles: ['role-id', 'role-id']

    - name: 'remove-punishment'
      roles: ['role-id']

punishments:
  editors: ['role-id', 'role-id']
  managers: ['role-id']

  defaultWarnDuration: 2592000000 # 30 days
  defaultMuteDuration: 21600000 # 6 hours
  defaultBanDuration: 5184000000 # 60 days (2 months)

  additionalInfo:
    warn: 'If you feel like this warning is unjustified, you may appeal it by messaging a Senior Moderator or higher.'
    mute: "Take the time to think about the mistakes you made so you don't end up muted again."
    kick: 'You may rejoin the server at any time, however, repeating the action that caused you to get kicked will result in a ban.'
    ban: 'You may appeal this ban [here](https://banappealurl.com)'

lock:
  channels: ['channel-id', 'channel-id', 'channel-id', 'channel-id', 'channel-id']
  overrides: 377960303168 # Will deny Send Messages, Send Messages In Threads, Create Public/Private Threads, Attach Files, Add Reactions, Connect (vc), Speak (vc), Video (vc)

automod:
  filters:
    - name: 'No Swear Filter'
      enabled: true
      immuneRoles: []
      immuneChannels: []
      punishment: 'Warn'
      duration: 86400000
      customInfo: 'We are a SFW server, please do not use swear words.'
      fallbackResponse: 'Please do not send prohibited words!'
      content: ['word1', 'word2', 'word3']

    - name: 'No Slur Filter'
      enabled: true
      immuneRoles: []
      immuneChannels: []
      punishment: 'Ban'
      customInfo: 'We are a welcoming and inclusive community, as such we will not tolerate any slurs.'
      fallbackResponse: "Slurs aren't welcome here buddy. Goodbye."
      content: ['slur1', 'slur2', 'slur3']

  links:
    - name: 'All Links Filter'
      enabled: true
      immuneRoles: ['role-id', 'role-id']
      immuneChannels: ['channel-id', 'channel-id']
      punishment: 'Warn'
      duration: 86400000
      customInfo: 'You are not allowed to send any links as they may contain malicious content.'
      fallbackResponse: 'Hi! Please do not send links, thanks!'
      whitelist: ['discord.com', 'discordapp.com', 'tenor.com'] # We whitelist the domain in the global filter but not in the tenor filter that gets triggered for users without any of the immune roles.

    - name: 'Tenor Links Filter'
      enabled: true
      immuneRoles: ['role-id', 'role-id']
      immuneChannels: ['channel-id', 'channel-id']
      punishment: 'Warn'
      duration: 86400000
      fallbackResponse: 'Hi! You cannot send tenor links yet as you are lacking an immune role to the tenor links filter!'
      whitelist: []

  mentions:
    - name: 'Owner Mention Filter'
      enabled: true
      immuneRoles: []
      immuneChannels: []
      punishment: 'Warn'
      duration: 86400000
      fallbackResponse: 'Hi! You cannot ping the owners as they are busy and will not respond to your message.'
      list: ['owner-id', 'owner-id2']

    - name: 'Developer Mention Filter'
      enabled: true
      immuneRoles: []
      immuneChannels: []
      punishment: 'Warn'
      duration: 86400000
      fallbackResponse: 'Hi! You cannot ping the game developers as they are busy and will not respond to your message.'
      list: ['developer-id', 'developer-id2']

  antiSpam:
    maxMentions:
      enabled: true
      immuneRoles: ['role-id', 'role-id']
      immuneChannels: []
      punishment: 'Warn'
      duration: 86400000
      limit: 6

    maxCharacters:
      enabled: true
      immuneRoles: ['role-id']
      immuneChannels: ['channel-id', 'channel-id']
      punishment: 'Warn'
      duration: 86400000
      limit: 500

    maxAttachments:
      enabled: true
      immuneRoles: []
      immuneChannels: ['channel-id', 'channel-id', 'channel-id']
      punishment: 'Warn'
      duration: 86400000
      limit: 5

logging:
  punishments:
    enabled: true
    channelId: 'log-channel-id'
  punishmentEdit:
    enabled: false
    channelId: 'log-channel-id'
  messages:
    enabled: true
    channelId: 'log-channel-id'
    excluded: ['channel-id', 'channel-id', 'channel-id']
  commands:
    enabled: false
    channelId: 'log-channel-id'
